# Site settings
title: AMRS
email: amrs.tech@gmail.com
url: https://amrs-tech.github.io
description: "console.log('Welcome to mySite')"

# Color settings (hex-codes without the leading hash-tag)
color:
  primary-dark: '#000000'
  links: '#219ab3'

# Footer settings
footer: myName['nickname']

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: linkedin
    url: https://www.linkedin.com/in/ahamed-musthafa-rs/
  - title: github
    url: https://github.com/amrs-tech
  #- title: kaggle
   # url: https://kaggle.com/amrstech

# Build settings
markdown: kramdown
permalink: pretty
