# Site settings
title: AMRS
email: amrs.tech@gmail.com
url: https://amrs-tech.github.io
description: "Welcome to my Site"

# Color settings (hex-codes without the leading hash-tag)
color:
  primary-dark: '#000000'
  links: '#219ab3'

# Footer settings
footer: Your Website

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: google plus
    url: https://plus.google.com/107997462684733756437
  - title: github
    url: https://github.com/amrs-tech

# Build settings
markdown: kramdown
permalink: pretty
